---- Base app schema
CREATE EXTENSION IF NOT EXISTS pgcrypto CASCADE;
-- User
CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  username varchar(128) NOT NULL UNIQUE,

  -- Auth 
  pwd varchar(256),
  pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL DEFAULT gen_random_uuid()
);


-- Bounty
CREATE TABLE bounty (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  title varchar(256) NOT NULL
);
-- Project
CREATE TABLE project (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  project_id varchar(256) NOT NULL,
  project_name varchar(256) NOT NULL,
  project_lead_address varchar(256) NOT NULL,
  project_budget varchar(256) NOT NULL,
  project_denom varchar(256) NOT NULL,
  project_type varchar(256) NOT NULL,
  project_description varchar(256) NOT NULL
);